/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioRouteImport } from './routes/_studio'
import { Route as CompositorDevRouteImport } from './routes/compositor-dev'
import { Route as StudioJoinRouteImport } from './routes/_studio/join'
import { Route as StudioLiveRouteImport } from './routes/_studio/live'
import { Route as StudioLoginRouteImport } from './routes/_studio/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/_studio',
  getParentRoute: () => rootRouteImport,
} as any)
const CompositorDevRoute = CompositorDevRouteImport.update({
  id: '/compositor-dev',
  path: '/compositor-dev',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioJoinRoute = StudioJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => StudioRoute,
} as any)
const StudioLiveRoute = StudioLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => StudioRoute,
} as any)
const StudioLoginRoute = StudioLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => StudioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compositor-dev': typeof CompositorDevRoute
  '/join': typeof StudioJoinRoute
  '/live': typeof StudioLiveRoute
  '/login': typeof StudioLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compositor-dev': typeof CompositorDevRoute
  '/join': typeof StudioJoinRoute
  '/live': typeof StudioLiveRoute
  '/login': typeof StudioLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_studio': typeof StudioRouteWithChildren
  '/compositor-dev': typeof CompositorDevRoute
  '/_studio/join': typeof StudioJoinRoute
  '/_studio/live': typeof StudioLiveRoute
  '/_studio/login': typeof StudioLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/compositor-dev' | '/join' | '/live' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/compositor-dev' | '/join' | '/live' | '/login'
  id:
    | '__root__'
    | '/'
    | '/_studio'
    | '/compositor-dev'
    | '/_studio/join'
    | '/_studio/live'
    | '/_studio/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudioRoute: typeof StudioRouteWithChildren
  CompositorDevRoute: typeof CompositorDevRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_studio': {
      id: '/_studio'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compositor-dev': {
      id: '/compositor-dev'
      path: '/compositor-dev'
      fullPath: '/compositor-dev'
      preLoaderRoute: typeof CompositorDevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_studio/join': {
      id: '/_studio/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof StudioJoinRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/live': {
      id: '/_studio/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof StudioLiveRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/login': {
      id: '/_studio/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof StudioLoginRouteImport
      parentRoute: typeof StudioRoute
    }
  }
}

interface StudioRouteChildren {
  StudioJoinRoute: typeof StudioJoinRoute
  StudioLiveRoute: typeof StudioLiveRoute
  StudioLoginRoute: typeof StudioLoginRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioJoinRoute: StudioJoinRoute,
  StudioLiveRoute: StudioLiveRoute,
  StudioLoginRoute: StudioLoginRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudioRoute: StudioRouteWithChildren,
  CompositorDevRoute: CompositorDevRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
