/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioRouteImport } from './routes/_studio'
import { Route as CompositorDevRouteImport } from './routes/compositor-dev'
import { Route as StudioAppRouteImport } from './routes/_studio/_app'
import { Route as StudioLiveRouteImport } from './routes/_studio/live'
import { Route as StudioLoginRouteImport } from './routes/_studio/login'
import { Route as StudioSignupRouteImport } from './routes/_studio/signup'
import { Route as StudioAppJoinRouteImport } from './routes/_studio/_app/join'
import { Route as StudioAppSettingsRouteImport } from './routes/_studio/_app/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/_studio',
  getParentRoute: () => rootRouteImport,
} as any)
const CompositorDevRoute = CompositorDevRouteImport.update({
  id: '/compositor-dev',
  path: '/compositor-dev',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioAppRoute = StudioAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => StudioRoute,
} as any)
const StudioLiveRoute = StudioLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => StudioRoute,
} as any)
const StudioLoginRoute = StudioLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => StudioRoute,
} as any)
const StudioSignupRoute = StudioSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => StudioRoute,
} as any)
const StudioAppJoinRoute = StudioAppJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => StudioAppRoute,
} as any)
const StudioAppSettingsRoute = StudioAppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudioAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compositor-dev': typeof CompositorDevRoute
  '/live': typeof StudioLiveRoute
  '/login': typeof StudioLoginRoute
  '/signup': typeof StudioSignupRoute
  '/join': typeof StudioAppJoinRoute
  '/settings': typeof StudioAppSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compositor-dev': typeof CompositorDevRoute
  '/live': typeof StudioLiveRoute
  '/login': typeof StudioLoginRoute
  '/signup': typeof StudioSignupRoute
  '/join': typeof StudioAppJoinRoute
  '/settings': typeof StudioAppSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_studio': typeof StudioRouteWithChildren
  '/compositor-dev': typeof CompositorDevRoute
  '/_studio/_app': typeof StudioAppRouteWithChildren
  '/_studio/live': typeof StudioLiveRoute
  '/_studio/login': typeof StudioLoginRoute
  '/_studio/signup': typeof StudioSignupRoute
  '/_studio/_app/join': typeof StudioAppJoinRoute
  '/_studio/_app/settings': typeof StudioAppSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compositor-dev'
    | '/live'
    | '/login'
    | '/signup'
    | '/join'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compositor-dev'
    | '/live'
    | '/login'
    | '/signup'
    | '/join'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_studio'
    | '/compositor-dev'
    | '/_studio/_app'
    | '/_studio/live'
    | '/_studio/login'
    | '/_studio/signup'
    | '/_studio/_app/join'
    | '/_studio/_app/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudioRoute: typeof StudioRouteWithChildren
  CompositorDevRoute: typeof CompositorDevRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_studio': {
      id: '/_studio'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compositor-dev': {
      id: '/compositor-dev'
      path: '/compositor-dev'
      fullPath: '/compositor-dev'
      preLoaderRoute: typeof CompositorDevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_studio/_app': {
      id: '/_studio/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudioAppRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/live': {
      id: '/_studio/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof StudioLiveRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/login': {
      id: '/_studio/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof StudioLoginRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/signup': {
      id: '/_studio/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof StudioSignupRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/_app/join': {
      id: '/_studio/_app/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof StudioAppJoinRouteImport
      parentRoute: typeof StudioAppRoute
    }
    '/_studio/_app/settings': {
      id: '/_studio/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof StudioAppSettingsRouteImport
      parentRoute: typeof StudioAppRoute
    }
  }
}

interface StudioAppRouteChildren {
  StudioAppJoinRoute: typeof StudioAppJoinRoute
  StudioAppSettingsRoute: typeof StudioAppSettingsRoute
}

const StudioAppRouteChildren: StudioAppRouteChildren = {
  StudioAppJoinRoute: StudioAppJoinRoute,
  StudioAppSettingsRoute: StudioAppSettingsRoute,
}

const StudioAppRouteWithChildren = StudioAppRoute._addFileChildren(
  StudioAppRouteChildren,
)

interface StudioRouteChildren {
  StudioAppRoute: typeof StudioAppRouteWithChildren
  StudioLiveRoute: typeof StudioLiveRoute
  StudioLoginRoute: typeof StudioLoginRoute
  StudioSignupRoute: typeof StudioSignupRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioAppRoute: StudioAppRouteWithChildren,
  StudioLiveRoute: StudioLiveRoute,
  StudioLoginRoute: StudioLoginRoute,
  StudioSignupRoute: StudioSignupRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudioRoute: StudioRouteWithChildren,
  CompositorDevRoute: CompositorDevRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
