/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioRouteImport } from './routes/_studio'
import { Route as CompositorDevRouteImport } from './routes/compositor-dev'
import { Route as StudioAppRouteImport } from './routes/_studio/_app'
import { Route as StudioLoginRouteImport } from './routes/_studio/login'
import { Route as StudioSignupRouteImport } from './routes/_studio/signup'
import { Route as RSlugRouteImport } from './routes/r/$slug'
import { Route as StudioAppNewRouteImport } from './routes/_studio/_app/new'
import { Route as StudioAppSettingsRouteImport } from './routes/_studio/_app/settings'
import { Route as RSlugIndexRouteImport } from './routes/r/$slug/index'
import { Route as RSlugLiveRouteImport } from './routes/r/$slug/live'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/_studio',
  getParentRoute: () => rootRouteImport,
} as any)
const CompositorDevRoute = CompositorDevRouteImport.update({
  id: '/compositor-dev',
  path: '/compositor-dev',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioAppRoute = StudioAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => StudioRoute,
} as any)
const StudioLoginRoute = StudioLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => StudioRoute,
} as any)
const StudioSignupRoute = StudioSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => StudioRoute,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioAppNewRoute = StudioAppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => StudioAppRoute,
} as any)
const StudioAppSettingsRoute = StudioAppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudioAppRoute,
} as any)
const RSlugIndexRoute = RSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RSlugRoute,
} as any)
const RSlugLiveRoute = RSlugLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => RSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compositor-dev': typeof CompositorDevRoute
  '/login': typeof StudioLoginRoute
  '/signup': typeof StudioSignupRoute
  '/r/$slug': typeof RSlugRouteWithChildren
  '/new': typeof StudioAppNewRoute
  '/settings': typeof StudioAppSettingsRoute
  '/r/$slug/live': typeof RSlugLiveRoute
  '/r/$slug/': typeof RSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compositor-dev': typeof CompositorDevRoute
  '/login': typeof StudioLoginRoute
  '/signup': typeof StudioSignupRoute
  '/new': typeof StudioAppNewRoute
  '/settings': typeof StudioAppSettingsRoute
  '/r/$slug/live': typeof RSlugLiveRoute
  '/r/$slug': typeof RSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_studio': typeof StudioRouteWithChildren
  '/compositor-dev': typeof CompositorDevRoute
  '/_studio/_app': typeof StudioAppRouteWithChildren
  '/_studio/login': typeof StudioLoginRoute
  '/_studio/signup': typeof StudioSignupRoute
  '/r/$slug': typeof RSlugRouteWithChildren
  '/_studio/_app/new': typeof StudioAppNewRoute
  '/_studio/_app/settings': typeof StudioAppSettingsRoute
  '/r/$slug/live': typeof RSlugLiveRoute
  '/r/$slug/': typeof RSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compositor-dev'
    | '/login'
    | '/signup'
    | '/r/$slug'
    | '/new'
    | '/settings'
    | '/r/$slug/live'
    | '/r/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compositor-dev'
    | '/login'
    | '/signup'
    | '/new'
    | '/settings'
    | '/r/$slug/live'
    | '/r/$slug'
  id:
    | '__root__'
    | '/'
    | '/_studio'
    | '/compositor-dev'
    | '/_studio/_app'
    | '/_studio/login'
    | '/_studio/signup'
    | '/r/$slug'
    | '/_studio/_app/new'
    | '/_studio/_app/settings'
    | '/r/$slug/live'
    | '/r/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudioRoute: typeof StudioRouteWithChildren
  CompositorDevRoute: typeof CompositorDevRoute
  RSlugRoute: typeof RSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_studio': {
      id: '/_studio'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compositor-dev': {
      id: '/compositor-dev'
      path: '/compositor-dev'
      fullPath: '/compositor-dev'
      preLoaderRoute: typeof CompositorDevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_studio/_app': {
      id: '/_studio/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudioAppRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/login': {
      id: '/_studio/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof StudioLoginRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/signup': {
      id: '/_studio/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof StudioSignupRouteImport
      parentRoute: typeof StudioRoute
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_studio/_app/new': {
      id: '/_studio/_app/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof StudioAppNewRouteImport
      parentRoute: typeof StudioAppRoute
    }
    '/_studio/_app/settings': {
      id: '/_studio/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof StudioAppSettingsRouteImport
      parentRoute: typeof StudioAppRoute
    }
    '/r/$slug/': {
      id: '/r/$slug/'
      path: '/'
      fullPath: '/r/$slug/'
      preLoaderRoute: typeof RSlugIndexRouteImport
      parentRoute: typeof RSlugRoute
    }
    '/r/$slug/live': {
      id: '/r/$slug/live'
      path: '/live'
      fullPath: '/r/$slug/live'
      preLoaderRoute: typeof RSlugLiveRouteImport
      parentRoute: typeof RSlugRoute
    }
  }
}

interface StudioAppRouteChildren {
  StudioAppNewRoute: typeof StudioAppNewRoute
  StudioAppSettingsRoute: typeof StudioAppSettingsRoute
}

const StudioAppRouteChildren: StudioAppRouteChildren = {
  StudioAppNewRoute: StudioAppNewRoute,
  StudioAppSettingsRoute: StudioAppSettingsRoute,
}

const StudioAppRouteWithChildren = StudioAppRoute._addFileChildren(
  StudioAppRouteChildren,
)

interface StudioRouteChildren {
  StudioAppRoute: typeof StudioAppRouteWithChildren
  StudioLoginRoute: typeof StudioLoginRoute
  StudioSignupRoute: typeof StudioSignupRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioAppRoute: StudioAppRouteWithChildren,
  StudioLoginRoute: StudioLoginRoute,
  StudioSignupRoute: StudioSignupRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

interface RSlugRouteChildren {
  RSlugLiveRoute: typeof RSlugLiveRoute
  RSlugIndexRoute: typeof RSlugIndexRoute
}

const RSlugRouteChildren: RSlugRouteChildren = {
  RSlugLiveRoute: RSlugLiveRoute,
  RSlugIndexRoute: RSlugIndexRoute,
}

const RSlugRouteWithChildren = RSlugRoute._addFileChildren(RSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudioRoute: StudioRouteWithChildren,
  CompositorDevRoute: CompositorDevRoute,
  RSlugRoute: RSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
